version: "3"
services:
  local:
    image: node:8.5.0
    command: npm run start-compose
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000
    image: couchbase
    volumes:
      - type: volume
        source: couchbase1
        target: /opt/couchbase1/var
    networks:
      couchbase-net:
        ipv4_address: 172.16.101.11
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210